import Config

# Configure your database
config :quadman, Quadman.Repo,
  database: Path.expand("../quadman_dev.db", __DIR__),
  pool_size: 5,
  journal_mode: :wal,
  cache_size: -64000,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :quadman, QuadmanWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "+wlqgHfXq/7FB3PXQZI4a0hyZ4c79m3glvnn43dEG6K2OjXKDUvN+Msf68n9V/3l",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:quadman, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:quadman, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :quadman, QuadmanWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/quadman_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :quadman, dev_routes: true

# Use systemd stub on macOS / dev — no real systemctl calls
config :quadman, systemd_adapter: Quadman.Systemd.Stub

# Caddy is disabled in dev; use stub adapter when testing with CADDY_ENABLED=true
config :quadman,
  caddy_enabled: false,
  caddy_adapter: Quadman.Caddy.Stub,
  caddy_admin_url: "http://localhost:2019"

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
